In [1]:
import numpy as np
import pycarrot.nn as nn
from pycarrot.carrot import Carrot

In [2]:
# test add
x1 = Carrot([1], requires_grad=True)
x2 = Carrot([4, 5, 6], requires_grad=True)

y = x1 + x2
print(y.data)
print("----------------")
y.backward()
print(y.grad.data)
print("----------------")
print(x1.grad.data)
print("----------------")
print(x2.grad.data)

[5 6 7]
----------------
[1. 1. 1.]
----------------
[3.]
----------------
[1. 1. 1.]


In [3]:
# test mul(*)
x1 = Carrot([[3], [2], [3]], requires_grad=True)
x2 = Carrot([4, 5, 6], requires_grad=True)
x3 = Carrot([7, 8, 9], requires_grad=True)

y = x1 * x2 + x3
print(y.data)
print("----------------")
y.backward()
print(y.grad.data)
print("----------------")
print(y.grad.data * x2.data)
print("----------------")
print(x1.grad.data)
print("----------------")
print(y.grad.data * x1.data)
print("----------------")
print(x2.grad.data)
print("----------------")
print(x3.grad.data)

[[19 23 27]
 [15 18 21]
 [19 23 27]]
----------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
----------------
[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]
----------------
[[15.]
 [15.]
 [15.]]
----------------
[[3. 3. 3.]
 [2. 2. 2.]
 [3. 3. 3.]]
----------------
[8. 8. 8.]
----------------
[3. 3. 3.]


In [4]:
# test sub(-)
x1 = Carrot([4, 5, 6], requires_grad=True)
x2 = Carrot([7, 8, 9], requires_grad=True)
y = x2 - x1
print(y.name)
print(y.data)
print("----------------")
y.backward()
print(y.grad.data)
print("----------------")
print(x1.grad.data)
print("----------------")
print(x2.grad.data)
print("----------------")

sub
[3 3 3]
----------------
[1. 1. 1.]
----------------
[-1. -1. -1.]
----------------
[1. 1. 1.]
----------------


In [27]:
# test pow
x = Carrot([4, 5, 6], requires_grad=True)
n = 2
# y = x ** 2
y = x.pow(2)
print(y.name)
print(y.data)
print("----------------")
y.backward()
print(y.grad.data)
print("----------------")
print(x.grad.data)

pow
[16 25 36]
----------------
[1. 1. 1.]
----------------
[ 8. 10. 12.]


In [29]:
# test slice(getitem())
x = Carrot([[1, 2, 3], [4, 5, 6], [7, 8, 9]], requires_grad=True)
print(x.data)
y = x[1:, 1:]
print("--------------")
print(y.data)
y.backward()
print("--------------")
print(y.grad.data)
print("--------------")
print(x.grad.data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------
[[5 6]
 [8 9]]
--------------
[[1. 1.]
 [1. 1.]]
--------------
[[0. 0. 0.]
 [0. 1. 1.]
 [0. 1. 1.]]


In [45]:
x = Carrot([[1, 2, 3], [4, 5, 6], [7, 8, 9]], requires_grad=True)

print(x.data)
print("---------------")
y = x.reshape((9, 1))
print(y.name)
print("---------------")
print(y.data)
print("---------------")
y.backward()
print(y.grad)
print("---------------")
print(x.grad)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------
reshape
---------------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
---------------
Carrot:([[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]], requires_grad=False)
---------------
Carrot:([[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], requires_grad=False)


In [60]:
# test matrix dot product
# x = Carrot([1, 2, 3], requires_grad=True)
x = Carrot([[1, 2, 3]], requires_grad=True)
y = Carrot([[1], [2], [3]], requires_grad=True)

z = x @ y
print(z.name)
print("----------")
print(z.data)
print("----------")
z.backward()
print(z.grad.data)
print("----------")
print(x.grad.data)
print("----------")
print(y.grad.data)

@
----------
[[14]]
----------
[[1.]]
----------
[[1. 2. 3.]]
----------
[[1.]
 [2.]
 [3.]]


In [67]:
# test carrot.sum()
x = Carrot([[1], [2], [3]], requires_grad=True)
y = x.sum()
print(x.data)
print("------------")
print(y.name)
print(y.data)
print("------------")
y.backward()
print(y.grad.data.size)
print("------------")
print(x.grad.data)

[[1]
 [2]
 [3]]
------------
sum
6
------------
1
------------
[[1.]
 [1.]
 [1.]]


In [73]:
x = Carrot([[1, 2, 3], [4, 5, 6], [7, 8, 9]], requires_grad=True)

y = x.mean()
print(len(x))
print("------------")
print(x.data)
print("------------")
print(y.name)
print(y.data)
print("------------")
y.backward()
print(y.grad.data.size)
print("------------")
print(x.grad.data)

3
------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------
mean
5.0
------------
1
------------
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]


In [10]:
# test clamp
x = Carrot([[1, 2, 3], [4, 5, 6], [7, 8, 9]], requires_grad=True)

y = x.clamp(3, 6)
print(x.data)
print("------------")
print(y.name)
print(y.data)
print("------------")
y.backward()
print(y.grad.data)
print("------------")
print(x.grad.data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------
clip
[[3 3 3]
 [4 5 6]
 [6 6 6]]
------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
------------
[[0. 0. 1.]
 [1. 1. 1.]
 [0. 0. 0.]]


In [7]:
import numpy as np

a = np.array([1])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c = a + b
d = np.sum(b, axis=0)
d = np.sum(d, axis=0, keepdims=True)
print(a, a.shape)
print(d, d.shape)
# print(a)
# print(b)
# print(c)
# print(a.shape)
# print(b.shape)
# print(c.shape)

[1] (1,)
[45] (1,)
